# --- 1. LANGUAGE DICTIONARY ---
LANG_MAP = {
    "English": {
        "title": "🛡️ Retirement Tax Strategy Planner",
        "privacy_note": "🔒 Privacy & Data Security Notice: This application runs entirely within your local browser session. No user data, asset values, or personal tax profiles are ever collected, tracked, or stored on any external server. Your financial information remains completely private.",
        "about_expander": "📖 About & How to Use",
        "motivation_h": "✍️ Motivation",
        "motivation_body": "This tool provides prospective retirees or current retirees with a tax strategy simulation and individualizes the various levers to convert to Roth; to realize capital gains; to test different growth scenarios. The goal is to achieve optimum total wealth, while minimizing the total federal tax paid in the horizon.",
        "meth_h": "🔬 Methodology",
        "meth_body": """
* **Asset Progression:** Tracks growth rates across three buckets (IRA, Roth, Brokerage).
* **Tax Attribution:** Distributes the annual Federal Tax burden proportionally across taxable yield sources.
* **IRMAA Monitoring:** Includes Municipal Interest in the MAGI calculation to track Medicare surcharge thresholds.
* **Waterfall Withdrawal Strategy:** a systematic approach to spending down retirement assets that prioritizes tax efficiency and capital preservation, in the order of taxable accounts, IRA accounts and Roth IRA accounts.
""",
        "use_h": "🕹️ How to Use",
        "use_body": """
* **Adjust Strategic Levers:** Use the sidebar to simulate different Roth conversion levels and Capital Gain harvesting.
* **Test Different Growth and Expense Scenarios:** Use the sidebar to test different growth assumptions, inflation rate and annual living expenses.
* **Explore Strategy Lab:** Navigate to the "Strategy Lab" tab to run automated sensitivity analyses that identify your mathematically optimal annual Roth conversion amount and window.
* **Observe Expected Net Worth:** Watch the comparison and roadmap to see how paying taxes early preserves long-term survival-weighted capital.
""",
        "kpi_h": "🚀 {sim_years}-Year Combined Optimization vs. Idle",
        "kpi_init_nw": "Initial Net Worth",
        "kpi_nw": "Weighted Expected NW",
        "kpi_tax": "Total Federal Tax Paid",
        "kpi_rmd": "Total RMD Amount",
        "kpi_roth": "Total Roth Reservoir",
        "kpi_total_outflow": "Total {sim_years}-Yr Outflow",
        "kpi_cap_outflow": "Total living expenses plus all federal taxes paid over {sim_years} years.",        
        "kpi_cap_init": "Your starting capital across all accounts.",
        "kpi_cap_nw": "Total capital remaining across all accounts after {sim_years} years.",
        "kpi_cap_tax": "Cumulative tax burden over the {sim_years}-year period.",
        "kpi_cap_roth": "Final tax-free balance available for heirs or late-life needs.",
        "roadmap_h": "Retirement Roadmap starting",
        "summary_h": "📊 Strategic Account Summary ({sim_years}-Year Cumulative)",
        "sidebar_timeline": "⏳ 1. Retirement Timeline",
        "sidebar_assets": "💰 Initial Assets",
        "sidebar_growth": "📈 Growth",
        "sidebar_cash": "💵 Cash Flow, Yield & Expenses",
        "sidebar_ss": "📈 Social Security",
        "sidebar_levers": "🎚️ Strategy Levers",
        "filing_status": "Tax Filing Status",
        "qd_ratio": "Qualified Dividend %",
        "col_ss": "INPUT: SS",
        "col_roth": "LEVER: Roth",
        "col_div": "INPUT: Taxable Div",
        "col_muni": "INPUT: Tax-Free Int",
        "col_cg": "INPUT: Cap Gains",
        "col_rmd": "INPUT: RMDs",
        "col_outflow": "OUT: Total Outflow",
        "col_magi": "OUT: MAGI",
        "col_tax": "OUT: Fed Tax",
        "col_obbba": "Fed OBBA Deduction",
        "col_nw": "Total Net Worth",
        "col_ex_nw": "Expected Net Worth",
        "col_events": "🚨 Important Events",
        "event_oom": "⚠️ OUT OF MONEY",        
        "event_retire": "Retirement",
        "event_roth_stop": "🛑 Roth Stop",
        "event_hmed": "H-Medicare",
        "event_wmed": "W-Medicare",
        "event_hrmd": "H-RMD Start",
        "event_wrmd": "W-RMD Start",
        "acc_ira": "Tax-Deferred (IRA)",
        "acc_roth": "Tax-Free (Roth)",
        "acc_broker": "Taxable (Brokerage/Muni)",
        "sum_init": "Initial Balance", 
        "sum_final": "Final Asset Balance", 
        "sum_yield": "Total {sim_years}-Yr Yield/Income",
        "sum_liability": "Total {sim_years}-Yr Tax Liability",
        "total_label": "**TOTAL ASSETS**",
        "comp_header": "⚖️ Strategy vs. Baseline Comparison ({sim_years}-Year Summary)",
        "comp_desc": "Compares your active strategy and the combined optimal (Roth, SS, muni, capital gains, withdrawal) against idle over {sim_years} years. Success is measured by maximizing survival-weighted Expected Net Worth.",
        "kpi_nw_gain": "Expected Net Worth Gain (Mean)",
        "kpi_tax_saved": "Cumulative Taxes Saved",
        "kpi_tax_extra": "Upfront Tax Cost",
        "kpi_roth_boost": "Final Roth Reservoir Boost",
        "kpi_baseline": "Do Nothing",
        "kpi_strategy": "Your Plan",
        "kpi_optimum": "Combined Optimal",
        "tab_roadmap": "📋 Plan Summary",
        "roadmap_tab_h": "Your Optimized Retirement Plan",
        "roadmap_tab_desc": "This is the combined result of all your decisions from the previous tabs — retirement timing, Social Security claiming, Roth conversions, muni allocation, and capital gains harvesting. The KPIs compare your active strategy against doing nothing (Idle) and the mathematically optimal path.",
        "tab_whatif": "🔮 Scenarios",
        "whatif_h": "What If the Market or Strategy Changes?",
        "whatif_desc": "Stress-test your plan under different withdrawal strategies and growth environments. See how your net worth trajectory shifts when you change the order of account drawdowns or when markets over/underperform.",
        "tab_lab": "🔄 Roth Conversion?",
        "tab_data": "💾 Data Management",
        "lab_h": "Should You Do a Roth Conversion? For How Long?",
        "lab_desc": "A Roth conversion moves assets from traditional IRA to Roth — you pay tax now but all future growth and withdrawals are tax-free. The optimization uses an adjustable weighted score balancing current spending and future legacy, not the SS tab's unweighted final-year figure. The **golden window** is after retirement but before Social Security and RMDs begin, when your tax bracket is lowest.",
        "lab_golden_h": "🪟 Your Golden Window",
        "lab_golden_desc": "These are your lowest-tax years — income below the standard deduction is taxed at 0%, and conversions fill the 10%/12% brackets cheaply before higher-income sources (SS, RMDs) crowd them out.",
        "lab_bracket_h": "📊 Bracket Impact at Optimal Conversion",
        "lab_roth_h": "Optimal Annual Conversion Amount",
        "lab_roth_desc": "Tests how much to convert from IRA to Roth each year. The peak of the curve is the sweet spot — pay manageable taxes now to avoid larger forced withdrawals later. ({lab_horizon}-year horizon, survival-weighted.)",
        "lab_roth_chart_x": "Annual Conversion Amount",
        "lab_roth_chart_y": "Final Net Worth",
        "lab_roth_optimum": "Based on the simulation, the optimum annual Roth conversion amount is approximately",
        "lab_stop_h": "Roth Window Optimizer (Stop Age)",
        "lab_stop_desc": "Using the optimal amount (${best_amt:,.0f}/yr), finds the best age to stop converting. Usually best to keep going until RMDs force you to stop.",
        "lab_stop_chart_x": "Stop Age",
        "lab_stop_optimum": "The optimum age to stop Roth conversions is",
        "lab_pref_h": "⚙️ Optimization Preferences",
        "lab_pref_label": "Optimize for: Spending Now ← → Leaving More Later",
        "lab_pref_help": "Slide left to prioritize having more cash available in early retirement. Slide right to prioritize maximizing what you leave behind. Middle balances both.",
        "lab_pref_early": "Current Goal: Prioritizing **Early Retirement Liquidity**.",
        "lab_pref_late": "Current Goal: Prioritizing **Long-Term Legacy & Security**.",
        "lab_pref_balanced": "Current Goal: **Balanced approach**.",
        "lab_irmaa_label": "Max Medicare Surcharge Allowed",
        "lab_irmaa_help": "Limits how much extra Medicare premium you're willing to pay. 0 = no extra cost. Higher = allows more aggressive conversions that trigger surcharges.",
        "withdrawal_label": "Withdrawal Strategy",
        "withdrawal_help": "Controls the order in which accounts are tapped when cash flow doesn't cover expenses.",
        "ws_tax_efficient": "Tax-Efficient (Brokerage → IRA → Roth)",
        "ws_ira_first": "IRA-First (IRA → Brokerage → Roth)",
        "ws_roth_first": "Roth-First (Roth → Brokerage → IRA)",
        "ws_proportional": "Proportional Drawdown",
        "withdrawal_chart_h": "Withdrawal Strategy Comparison",
        "withdrawal_chart_desc": "Expected Net Worth trajectory under each withdrawal strategy over {sim_years} years.",
        "growth_profile_label": "Growth Profile",
        "growth_profile_help": "Shifts all account growth rates up or down together to model different market environments. Your base rates (set in Growth section) serve as the 'Moderate' baseline.",
        "gp_ultra_conservative": "Ultra-Conservative (-4%)",
        "gp_conservative": "Conservative (-2%)",
        "gp_moderate": "Moderate (your settings)",
        "gp_aggressive": "Aggressive (+2%)",
        "growth_profile_caption": "Growth shift: {shift:+.0f}% → IRA: {ira:.1f}% | Roth: {roth:.1f}% | Brokerage: {broker:.1f}%",
        "growth_chart_h": "Growth Profile Monte Carlo (100 simulations per profile)",
        "growth_chart_desc": "Solid lines show median outcome; shaded bands show 10th–90th percentile range. Annual returns drawn from Normal(mean, σ) per profile over {sim_years} years.",
        "tab_retire": "🏖️ When to Retire?",
        "retire_h": "When Can You Afford to Retire?",
        "retire_desc": "Simulates market uncertainty (Monte Carlo) for each retirement year to answer: can your money last through retirement? Results are expressed as confidence levels — e.g., '90% confidence' means in 90 out of 100 simulated market scenarios, your money lasts through your full retirement horizon.",
        "retire_chart_h": "Retirement Confidence by Year",
        "retire_chart_desc": "For each potential retirement year, the percentage of simulated market scenarios where your money lasts through the full horizon. Higher bars = safer.",
        "retire_table_h": "Confidence Analysis",
        "retire_col_year": "Retire Year",
        "retire_col_age": "Your Age",
        "retire_col_confidence": "Confidence (money lasts)",
        "retire_col_nw_90": "Final NW (90% confidence)",
        "retire_col_nw_75": "Final NW (75% confidence)",
        "retire_col_nw_50": "Final NW (50% confidence)",
        "retire_col_working_years": "Extra Working Years",
        "retire_current": "(current)",
        "retire_insight": "Key Insight",
        "gap_chart_h": "Income vs. Expense Over Time",
        "gap_chart_desc": "Shows how passive income covers expenses once Social Security kicks in. The gap (dashed) is what must come from savings each year.",
        "gap_label_expense": "Expense",
        "gap_label_income": "Passive Income",
        "gap_label_gap": "Gap (from savings)",
        "gap_y_title": "Annual Amount ($)",
        "tab_ss": "📅 When to Claim SS?",
        "ss_h": "When Should You Claim Social Security?",
        "ss_desc": "You can claim SS as early as 62 (reduced ~30%) or delay to 70 (+24% above FRA). Enter your estimated benefit at any age and we'll extrapolate the rest. The simulation compares claiming at different ages to show the long-term financial impact.",
        "ss_input_h": "Your Social Security Estimates",
        "ss_estimate_age_h": "Husband: Estimate at Age",
        "ss_estimate_amt_h": "Husband: Monthly Benefit ($)",
        "ss_estimate_age_w": "Wife: Estimate at Age",
        "ss_estimate_amt_w": "Wife: Monthly Benefit ($)",
        "ss_chart_h": "Net Worth by SS Claiming Strategy",
        "ss_chart_desc": "Each scenario shows the combined effect of both spouses' claiming ages on long-term net worth. Earlier claims mean smaller checks but more years of income; later claims mean larger checks but more years of withdrawals.",
        "ss_table_h": "Claiming Age Comparison",
        "ss_col_strategy": "Strategy",
        "ss_col_h_age": "H Claims",
        "ss_col_w_age": "W Claims",
        "ss_col_h_monthly": "H Monthly",
        "ss_col_w_monthly": "W Monthly",
        "ss_col_annual": "Combined Annual",
        "ss_col_final_nw": "Final Net Worth",
        "ss_col_total_tax": "Total Tax Paid",
        "ss_breakeven": "Breakeven",
        "ss_insight": "Key Insight",
        "tab_muni": "🏛️ Tax-Exempt Bonds?",
        "muni_h": "Should You Allocate to Tax-Exempt Bonds?",
        "muni_desc": "Municipal bond interest is excluded from federal income tax, and also from state income tax if the bond is issued in your state of residence. The **tax-equivalent yield** (TEY) shows what a taxable bond must earn to match a muni's after-tax return. At higher brackets, munis become increasingly attractive — and the tax-free income frees up bracket space for Roth conversions.",
        "muni_tey_h": "Tax-Equivalent Yield Analysis",
        "muni_bracket_label": "Your Estimated Marginal Bracket",
        "muni_yield_label": "Muni Yield (%)",
        "muni_tey_result": "Tax-Equivalent Yield",
        "muni_alloc_h": "Optimal Muni Allocation",
        "muni_alloc_desc": "Compares net worth outcomes across different muni allocation levels. A higher muni % trades raw yield for tax savings and MAGI reduction.",
        "muni_chart_h": "Net Worth by Muni Allocation",
        "muni_irmaa_h": "MAGI & IRMAA Impact",
        "muni_irmaa_desc": "Muni interest is excluded from AGI but **included in MAGI** for Medicare premium calculations. If MAGI exceeds ~$218,000 (MFJ), it triggers IRMAA surcharges.",
        "muni_insight": "Key Insight",
        "muni_col_alloc": "Muni %",
        "muni_col_muni_income": "Annual Muni Income",
        "muni_col_taxable_income": "Annual Taxable Yield",
        "muni_col_final_nw": "Final Net Worth",
        "muni_col_total_tax": "Total Tax Paid",
        "muni_col_magi_yr1": "Year 1 MAGI",
        "muni_ref_h": "Tax-Equivalent Yield Reference Table",
        "tab_cg": "💰 Capital Gains?",
        "cg_h": "Should You Harvest Capital Gains?",
        "cg_desc": "Long-term capital gains in the **0% bracket** (up to ~$94,050 MFJ taxable income) are tax-free. By strategically realizing gains when other income is low, you can reset your cost basis and permanently eliminate future tax on that appreciation.",
        "cg_zero_h": "Your 0% Capital Gains Capacity",
        "cg_zero_desc": "Based on your projected retirement income, this is how much long-term gain you can realize tax-free each year.",
        "cg_harvest_h": "Optimal Annual Harvest",
        "cg_harvest_desc": "Compares net worth outcomes across different annual capital gains harvesting levels. The sweet spot fills the 0% bracket without pushing income into higher tiers.",
        "cg_chart_h": "Net Worth by Harvest Amount",
        "cg_insight": "Key Insight",
        "cg_col_amount": "Annual Harvest",
        "cg_col_in_zero": "In 0% Bracket",
        "cg_col_in_fifteen": "In 15% Bracket",
        "cg_col_tax_on_cg": "Tax on Gains",
        "cg_col_final_nw": "Final Net Worth",
        "cg_col_total_tax": "Total Tax Paid",
        "cg_ref_h": "Capital Gains Tax Bracket Reference",
    },
    "Chinese": {
        "title": "🛡️ 退休税务策略规划器",
        "privacy_note": "🔒 隐私与数据安全提示：本程序完全在您的本地浏览器会话中运行。任何用户数据、资产数值或个人税务信息均不会被收集、追踪或存储在任何外部服务器上。您的财务信息将完全保持私密。",
        "about_expander": "📖 工具介绍与使用说明",
        "motivation_h": "✍️ 建立初衷",
        "motivation_body": "本工具为准退休人员或已退休人员提供税务策略模拟。通过量化 Roth 转换、资本利得变现及不同增长场景等杠杆，目标是实现最优的总财富，同时最小化未来预见的联邦税总支出。",
        "meth_h": "🔬 模拟方法论",
        "meth_body": """
* **资产演进:** 追踪三大类账户的增长（IRA, Roth, 经纪账户）。
* **税务归属:** 将年度联邦税负担按比例分配到各个应税收益来源中。
* **IRMAA 监测:** 将市政债券利息纳入 MAGI 计算，以追踪医保附加费 (Medicare surcharge) 的阈值。
* **瀑布式提款策略:** 一种系统化的提款方式，优先考虑税务效率和资本保全，提款顺序依次为：应税账户、IRA 账户、最后是 Roth IRA 账户。
""",
        "use_h": "🕹️ 使用说明",
        "use_body": """
* **调整策略杠杆:** 使用侧边栏模拟不同的 Roth 转换水平和资本利得获取。
* **测试增长与支出场景:** 测试不同的增长假设、通货膨胀率和年度生活支出。
* **探索策略实验室:** 导航到“策略实验室”选项卡，运行自动化敏感性分析，找出数学上最优的年度 Roth 转换金额和时间窗口。
* **观察预期净资产 (Expected Net Worth):** 关注路线图和对比，观察通过早期纳税如何保护长期的生存加权资本。
""",
        "kpi_h": "🚀 {sim_years}年 综合优化 vs. 无操作",
        "kpi_init_nw": "初始净资产", 
        "kpi_nw": "加权预期净资产",
        "kpi_tax": "联邦税总支出",
        "kpi_rmd": "最低强制提款(RMD)总额",
        "kpi_roth": "Roth 账户储备",
        "kpi_total_outflow": "{sim_years}年总支出",
        "kpi_cap_outflow": "{sim_years}年总生活支出与联邦税收之和",        
        "kpi_cap_init": "您的账户初始总资本", 
        "kpi_cap_nw": "{sim_years}年后所有账户中的剩余总资本",
        "kpi_cap_tax": "{sim_years}年期间累计的税务负担",
        "kpi_cap_roth": "可供继承或后期使用的最终免税余额",
        "roadmap_h": "退休财务路线图 - 始于",
        "summary_h": "📊 战略账户总结 ({sim_years}年累计)",
        "sidebar_timeline": "⏳ 1. 退休时间轴",
        "sidebar_assets": "💰 初始资产",
        "sidebar_growth": "📈 增长",
        "sidebar_cash": "💵 现金流、收益与支出",
        "sidebar_ss": "📈 社会安全金",
        "sidebar_levers": "🎚️ 策略杠杆",
        "filing_status": "报税状态",
        "qd_ratio": "符合条件的股息比例 (Qualified %)",
        "col_ss": "社保收入",
        "col_roth": "Roth转换",
        "col_div": "应税股息",
        "col_muni": "免税利息(Muni)",
        "col_cg": "资本利得",
        "col_rmd": "强制提款(RMD)",
        "col_outflow": "总支出(含税)",
        "col_magi": "MAGI(医保判定)",
        "col_tax": "联邦税支出",
        "col_obbba": "联邦OBBA抵扣",
        "col_nw": "总净资产",
        "col_ex_nw": "预期净资产",
        "col_events": "🚨 重要事件",
        "event_oom": "⚠️ 资金耗尽",        
        "event_roth_stop": "🛑 Roth 转换停止",
        "event_retire": "退休",
        "event_hmed": "丈夫医保",
        "event_wmed": "妻子医保",
        "event_hrmd": "丈夫RMD开始",
        "event_wrmd": "妻子RMD开始",
        "acc_ira": "税收递延 (IRA)",
        "acc_roth": "免税 (Roth)",
        "acc_broker": "应税 (经纪账户/市政债)",
        "sum_init": "初始余额", 
        "sum_final": "期末资产余额", 
        "sum_yield": "{sim_years}年总收益/收入",
        "sum_liability": "{sim_years}年总税务责任",
        "total_label": "**资产总计**",
        "comp_header": "⚖️ 优化策略 vs. 基准对比 ({sim_years}年累计)",
        "comp_desc": "在{sim_years}年周期内，将您的主动策略与综合最优（Roth、社保、市政债、资本利得、提取策略）同不操作方案进行对比。成功标准为最大化生存加权预期净值。",
        "kpi_nw_gain": "预期净资产提升 (平均)",
        "kpi_tax_saved": "累计节省税款",
        "kpi_tax_extra": "前期税务成本",
        "kpi_roth_boost": "免税 Roth 账户增幅",
        "kpi_baseline": "不操作",
        "kpi_strategy": "当前计划",
        "kpi_optimum": "综合最优",
        "tab_roadmap": "📋 计划总览",
        "roadmap_tab_h": "您的优化退休计划",
        "roadmap_tab_desc": "这是前面所有选项卡决策的综合结果——退休时间、社保领取、Roth转换、市政债券配置和资本利得变现。KPI将您的主动策略与不操作（Idle）和数学最优路径进行对比。",
        "tab_whatif": "🔮 情景分析",
        "whatif_h": "如果市场或策略发生变化会怎样？",
        "whatif_desc": "在不同提款策略和增长环境下压力测试您的计划。查看当改变账户提款顺序或市场表现好于/差于预期时，净资产走势如何变化。",
        "tab_lab": "🔄 Roth转换？",
        "tab_data": "💾 数据管理",
        "lab_h": "是否应该做Roth转换？做多久？",
        "lab_desc": "Roth转换是将传统IRA资产转入Roth——现在缴税，但未来所有增长和提款免税。优化采用可调节的加权评分，平衡当前消费与未来传承，并非SS标签页中未加权的最终年份数值。**黄金窗口期**是退休后、领取社保和强制提款(RMD)之前，此时您的税率最低。",
        "lab_golden_h": "🪟 您的黄金窗口期",
        "lab_golden_desc": "这些是您税率最低的年份——收入在标准扣除额以下税率为0%，转换可以低成本填充10%/12%税率区间，之后社保和RMD会占用这些低税率空间。",
        "lab_bracket_h": "📊 最优转换额的税率影响",
        "lab_roth_h": "最优年度转换金额",
        "lab_roth_desc": "测试每年从 IRA 转入 Roth 的最佳金额。曲线峰值即最优解——现在交适量的税，避免未来更大的强制提款税负。（{lab_horizon}年周期，生存加权。）",
        "lab_roth_chart_x": "年度转换金额",
        "lab_roth_chart_y": "最终总净资产",
        "lab_roth_optimum": "根据模拟，最佳年度 Roth 转换金额约为",
        "lab_stop_h": "Roth 转换周期（停止年龄）优化",
        "lab_stop_desc": "使用最佳金额 (${best_amt:,.0f}/年)，找出最佳停止转换年龄。通常持续转换到 RMD 开始前效果最优。",
        "lab_stop_chart_x": "停止年龄",
        "lab_stop_optimum": "最佳停止 Roth 转换的年龄是",
        "lab_pref_h": "⚙️ 优化偏好设置",
        "lab_pref_label": "优化目标：当前消费 ← → 长期传承",
        "lab_pref_help": "左滑侧重早期退休时有更多可用现金。右滑侧重最大化留给后人的资产。中间为两者平衡。",
        "lab_pref_early": "当前目标：优先考虑 **早期退休流动性**。",
        "lab_pref_late": "当前目标：优先考虑 **长期传承与财务安全**。",
        "lab_pref_balanced": "当前目标：**平衡方案**。",
        "lab_irmaa_label": "允许的最大 Medicare 附加费",
        "lab_irmaa_help": "限制您愿意承受的额外 Medicare 保费。0 = 无额外费用。越高 = 允许更激进的转换（会触发附加费）。",
        "withdrawal_label": "提款策略",
        "withdrawal_help": "控制当现金流不足以覆盖支出时，从哪些账户按什么顺序提款。",
        "ws_tax_efficient": "税务优先 (经纪→IRA→Roth)",
        "ws_ira_first": "IRA优先 (IRA→经纪→Roth)",
        "ws_roth_first": "Roth优先 (Roth→经纪→IRA)",
        "ws_proportional": "按比例 (各账户等比提取)",
        "withdrawal_chart_h": "提款策略对比",
        "withdrawal_chart_desc": "{sim_years}年各提款策略下的预期净资产走势。",
        "growth_profile_label": "增长预期",
        "growth_profile_help": "统一上下调整所有账户增长率，模拟不同市场环境。您在增长设置中的基础利率为'适中'基准。",
        "gp_ultra_conservative": "极保守 (-4%)",
        "gp_conservative": "保守 (-2%)",
        "gp_moderate": "适中 (当前设置)",
        "gp_aggressive": "积极 (+2%)",
        "growth_profile_caption": "增长调整: {shift:+.0f}% → IRA: {ira:.1f}% | Roth: {roth:.1f}% | 经纪: {broker:.1f}%",
        "growth_chart_h": "增长预期蒙特卡洛模拟 (每组100次)",
        "growth_chart_desc": "实线为中位数结果；阴影区域为10-90百分位范围。年回报按正态分布(均值, σ)随机抽样，模拟{sim_years}年。",
        "tab_retire": "🏖️ 何时退休？",
        "retire_h": "何时可以负担得起退休？",
        "retire_desc": "通过蒙特卡洛模拟市场不确定性，回答核心问题：你的钱能否撑过整个退休期？结果以置信度表示——例如「90%置信度」意味着在100次模拟中，有90次你的钱能撑到退休期末。",
        "retire_chart_h": "各退休年份的置信度分析",
        "retire_chart_desc": "每个潜在退休年份中，模拟市场情景下资金能撑过整个退休期的比例。柱越高越安全。",
        "retire_table_h": "置信度分析详情",
        "retire_col_year": "退休年份",
        "retire_col_age": "退休年龄",
        "retire_col_confidence": "置信度（资金持续）",
        "retire_col_nw_90": "最终净资产（90%置信度）",
        "retire_col_nw_75": "最终净资产（75%置信度）",
        "retire_col_nw_50": "最终净资产（50%置信度）",
        "retire_col_working_years": "额外工作年数",
        "retire_current": "（当前）",
        "retire_insight": "关键发现",
        "gap_chart_h": "收入与支出随时间变化",
        "gap_chart_desc": "显示社会安全金开始后，被动收入如何覆盖支出。虚线（缺口）表示每年需从储蓄中提取的金额。",
        "tab_ss": "📅 何时领社保？",
        "ss_h": "何时开始领取社会安全金？",
        "ss_desc": "最早62岁可领取（减少约30%），最迟70岁（比正常退休年龄高24%）。输入您在任意年龄的预估金额，系统将推算其他年龄的金额。模拟对比不同领取年龄对长期财务的影响。",
        "ss_input_h": "社保金额估算",
        "ss_estimate_age_h": "丈夫：估算年龄",
        "ss_estimate_amt_h": "丈夫：月领金额 ($)",
        "ss_estimate_age_w": "妻子：估算年龄",
        "ss_estimate_amt_w": "妻子：月领金额 ($)",
        "ss_chart_h": "不同领取策略下的净资产走势",
        "ss_chart_desc": "每个方案显示夫妻双方领取年龄对长期净资产的综合影响。早领意味着金额少但领取年数多；晚领意味着金额大但需要更多年的提款。",
        "ss_table_h": "领取年龄对比",
        "ss_col_strategy": "策略",
        "ss_col_h_age": "丈夫领取",
        "ss_col_w_age": "妻子领取",
        "ss_col_h_monthly": "丈夫月领",
        "ss_col_w_monthly": "妻子月领",
        "ss_col_annual": "合计年收入",
        "ss_col_final_nw": "最终净资产",
        "ss_col_total_tax": "总税负",
        "ss_breakeven": "盈亏平衡",
        "ss_insight": "关键发现",
        "tab_muni": "🏛️ 免税债券？",
        "muni_h": "是否应配置免税市政债券？",
        "muni_desc": "市政债券利息免联邦所得税，如果债券由您所在州发行，还免州所得税。**税等价收益率**（TEY）显示应税债券需要多高的收益率才能匹配免税债券的税后回报。在较高税率下，市政债券更具吸引力——免税收入还能为Roth转换腾出税率空间。",
        "muni_tey_h": "税等价收益率分析",
        "muni_bracket_label": "估计边际税率",
        "muni_yield_label": "市政债券收益率 (%)",
        "muni_tey_result": "税等价收益率",
        "muni_alloc_h": "最优市政债券配置",
        "muni_alloc_desc": "比较不同市政债券配置比例下的净资产结果。更高的市政债券比例以原始收益换取税收节省和MAGI降低。",
        "muni_chart_h": "不同配置下的净资产走势",
        "muni_irmaa_h": "MAGI与IRMAA影响",
        "muni_irmaa_desc": "市政债券利息不计入AGI，但**计入MAGI**用于Medicare保费计算。如果MAGI超过约$218,000（夫妻联合申报），会触发IRMAA附加费。",
        "muni_insight": "关键发现",
        "muni_col_alloc": "市政债%",
        "muni_col_muni_income": "年免税收入",
        "muni_col_taxable_income": "年应税收益",
        "muni_col_final_nw": "最终净资产",
        "muni_col_total_tax": "总税负",
        "muni_col_magi_yr1": "第1年MAGI",
        "muni_ref_h": "税等价收益率参考表",
        "tab_cg": "💰 资本利得？",
        "cg_h": "是否应变现资本利得？",
        "cg_desc": "在**0%税率区间**内（夫妻联合申报应税收入约$94,050以下），长期资本利得免税。在其他收入较低时策略性变现增值，可以重置成本基础，永久消除该部分增值的未来税负。",
        "cg_zero_h": "您的0%资本利得容量",
        "cg_zero_desc": "根据您的退休收入预测，这是每年可以免税变现的长期资本利得金额。",
        "cg_harvest_h": "最优年度变现金额",
        "cg_harvest_desc": "比较不同年度资本利得变现水平的净资产结果。最佳策略是填满0%税率区间，而不推高收入进入更高层级。",
        "cg_chart_h": "不同变现金额下的净资产走势",
        "cg_insight": "关键发现",
        "cg_col_amount": "年度变现额",
        "cg_col_in_zero": "0%区间内",
        "cg_col_in_fifteen": "15%区间内",
        "cg_col_tax_on_cg": "利得税",
        "cg_col_final_nw": "最终净资产",
        "cg_col_total_tax": "总税负",
        "cg_ref_h": "资本利得税率参考",
    }
}
